[project]
name = "vehicle_counter"
version = "0.1.0"
description = "Sistema de Detecção e Contagem de veiculos com YOLOv8"
readme = "README.md"
requires-python = "==3.11.9"
license = { text = "MIT" }
authors = [{ name = "Pedro Tenório", email = "pstsouza13@gmail.com" }]

dependencies = [
    "opencv-python",
    "ultralytics",
    "torch==2.3.1",
    "torchvision==0.18.1",
    "numpy<2.0.0",
    "shapely==2.0.0",
    "lap==0.5.12",
    "pyarrow",
    "pandas",
    "pydantic>=2.13.3",
]

[dependency-groups]
dev = [
    "dvc>=3.67.0",
    "ruff",
    "pyright",
    "pytest",
    "pytest-xdist",
]

[project.scripts]
vehicle-counter = "vehicle_counter.main:main"
vehicle-report = "vehicle_counter.aggregate_traffic:main"
vehicle-calibrate = "vehicle_counter.draw_lines:main"

# Build System
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vehicle_counter"]

# Tools: Ruff (Linter & Formatter)
[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src"]
fix = true
show-fixes = true
indent-width = 4
exclude = [
    "venv", ".venv", "env", ".env", "node_modules", "__pycache__"
]

[tool.ruff.lint]
# Strict selection of rules to keep the code clean
select = [
    "ASYNC", "A", "ANN", "B", "BLE", "C4", "C90", "COM", "E", "EM",
    "ERA", "EXE", "F", "FBT", "FIX", "I", "ICN", "ISC", "Q", "RET",
    "RSE", "S", "SIM", "SLF", "T10", "T20", "TC", "TD", "TRY", "UP",
    "W", "YTT", "RUF", "N"
]
ignore = ["T201", "COM812"]

[tool.ruff.lint.per-file-ignores]

# Ignore return types and asserts in tests
# Allows access to private methods (_) in tests
"tests/**/*.py" = ["ANN201", "S101", "SLF001"] 

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
# Teach Ruff what the main package of your project
# It must be the same name as the folder inside 'src/'
known-first-party = ["vehicle_counter"]

# Tools: Pyright (Type Checker)
[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.11"
include = ["src", "tests",]
exclude = [
    "**/venv", "**/.venv", "**/env", "**/.env",
    "**/node_modules", "**/__pycache__", "**/.*"
]
venv = ".venv"
venvPath = "."
executionEnvironments = [{ root = "src" }]

# Tools: Pytest
[tool.pytest.ini_options]
addopts = "-s --color=yes --tb=short"
pythonpath = ["src"]
testpaths = ["tests"]
